branches:
  only:
  - master
language: r
sudo: false
cache: 
  packages: yes
pandoc_version: 2.6
addons:
  chrome: stable
script:
  - Rscript -e 'rmarkdown::render("demo.Rmd")'
  - Rscript -e 'pagedown::chrome_print("demo.html", work_dir = "workdir", verbose = TRUE)'
