language: r
sudo: false
pandoc_version: 2.6
addons:
  chrome: stable
script:
  - Rscript -e 'pagedown::chrome_print("demo.Rmd", extra_args = c("--disable-gpu", "--no-sandbox"), work_dir = ".chromedir", verbose = TRUE)'
  - ls
