branches:
  only:
  - master
language: r
sudo: false
cache: 
  packages: yes
pandoc_version: 2.2.3

addons:
  chrome: stable
script:
  - Rscript -e 'pagedown::chrome_print(system.file("examples/index.Rmd", package = "pagedown"), verbose = TRUE)'
