branches:
  only:
  - master
language: r
sudo: false
cache: 
  packages: yes
pandoc_version: 2.6
addons:
  chrome: stable
script:
  - Rscript -e 'file.copy(system.file("examples/index.Rmd", package = "pagedown", mustWork = TRUE), "demo.Rmd")'
  - Rscript -e 'pagedown::chrome_print("demo.Rmd", verbose = TRUE)'
